server:
  port: 8080

spring:
  application:
    name: rabbit-euraka

eureka:
  instance:
    hostname: localhost
  client:
    regiser-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8080/eureka/
