server:
  port: 9000
spring:
  #给项目来个名字
  application:
    name: rabbit-producer
  #配置rabbitMq 服务器
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    #虚拟host 可以不设置,使用server默认host
#    virtual-host: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
    fetch-registry: true
    register-with-eureka: true
